# In this notebook, we're going to cover some of the most fundamental concepts of tensors using TensorFlow
More specifically, we're going to cover:
* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensors & NumPy
* Using @tf.function (a way to speed up your regular Python functions)
* Using GPUs with TensorFlow (or TPUS)
* Exercises to try for yoursel

## Introduction to Tensorflow

In [1]:
import tensorflow as tf
print(tf.__version__)

2.20.0


In [2]:
#create tensor with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# check the number of dimensions of a tensor 
scalar.ndim, scalar.shape

(0, TensorShape([]))

In [4]:
# create a vector 
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
vector.ndim, vector.shape

(1, TensorShape([2]))

In [7]:
# create matrix
matrix=tf.constant([[10,5],[1,45]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  5],
       [ 1, 45]], dtype=int32)>

In [8]:
matrix.ndim, matrix.shape

(2, TensorShape([2, 2]))

In [10]:
# create a another matrix
another_matrix=tf.constant([[10.,5.],[1.,45.],[34.,555.]],dtype=tf.float16)# specify the datatype
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[ 10.,   5.],
       [  1.,  45.],
       [ 34., 555.]], dtype=float16)>

In [11]:
another_matrix.ndim,another_matrix.shape

(2, TensorShape([3, 2]))

In [13]:
# let crete tensor
tensor = tf.constant([[[12,34],[54,65]],
                      [[435,536],[34,54]]])
tensor

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[ 12,  34],
        [ 54,  65]],

       [[435, 536],
        [ 34,  54]]], dtype=int32)>

In [16]:
tensor.ndim,tensor.shape

(3, TensorShape([2, 2, 2]))

### What we've created so far:
* Scalar: a single number
* Vector: a number with direction (e.g. wind speed and direction)
* Matrix: a 2-dimensional array of numbers
* Tensor: an n-dimensional array of numbers 

## creatiing with tf.variable

In [18]:
# create the same tensor with tf.varible 
changable_tensor=tf.Variable([35,57])
unchangable_tensor=tf.constant([35,57])
changable_tensor, unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([35, 57], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([35, 57], dtype=int32)>)

In [21]:
# lets try change one of the elements in our changeable tensor
#changable_tensor[0]=78
#changable_tensor
# this method gives error

In [22]:
changable_tensor[0].assign(7)
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 7, 57], dtype=int32)>

In [23]:
# lets try change one of the elements in our changeable tensor
#unchangable_tensor[0]=78
#unchangable_tensor
# this method gives error

In [25]:
#unchangable_tensor[0].assign(7)
#unchangable_tensor
# doses not support changing element

## creating random tensor

In [26]:
random_1= tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1=random_1.normal(shape=(3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>